import {
  Brand,
  Category,
  Product,
  CustomerProfile,
  Order,
  Campaign,
  DiscountCode,
  Review,
  CmsHeroBlock,
  CmsSectionBlock,
  AbandonedCart,
  AdminUser,
  AuditLog,
} from '@/types';

// ==========================================
// 1. MERKEVARER (BRANDS)
// ==========================================
export const INITIAL_BRANDS: Brand[] = [
  {
    id: 'b-hundegodt',
    name: 'Hundegodt Originals',
    slug: 'hundegodt-originals',
    logoUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=200&h=200&q=80',
    description: 'Vår egen kortreiste serie med 100% naturlige, skånsomt lufttørkede norske godbiter og rent kjøttsnack.',
    countryOfOrigin: 'Norge',
    isFeatured: true,
    productCount: 16,
  },
  {
    id: 'b-nordic-chew',
    name: 'Nordic Chew Co.',
    slug: 'nordic-chew-co',
    logoUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=200&h=200&q=80',
    description: 'Hjortegevir, elghud og ubehandlede naturtall-tygg fra skandinaviske skoger. 100% uten kjemikalier.',
    countryOfOrigin: 'Norge',
    isFeatured: true,
    productCount: 8,
  },
  {
    id: 'b-vom-treats',
    name: 'VOM Treats',
    slug: 'vom-treats',
    logoUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=200&h=200&q=80',
    description: 'Frysetørkede rå godbiter av ypperste slakterikvalitet fra norske gårder. Single-protein favoritter.',
    countryOfOrigin: 'Norge',
    isFeatured: true,
    productCount: 10,
  },
  {
    id: 'b-villmark',
    name: 'Villmarkssnacks',
    slug: 'villmarkssnacks',
    logoUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=200&h=200&q=80',
    description: 'Ekte viltgodbiter laget av norsk elg, rein og rype. Naturlig magert og allergivennlig.',
    countryOfOrigin: 'Norge',
    isFeatured: true,
    productCount: 6,
  },
  {
    id: 'b-potekjokkenet',
    name: 'PoteKjøkkenet',
    slug: 'potekjokkenet',
    logoUrl: 'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?auto=format&fit=crop&w=200&h=200&q=80',
    description: 'Ovnstørkede, sprø godbiter med norske bær, villaks og sunne urter for skinnende pels.',
    countryOfOrigin: 'Norge',
    isFeatured: true,
    productCount: 9,
  },
  {
    id: 'b-dentalbite',
    name: 'DentalBite Nordic',
    slug: 'dentalbite-nordic',
    logoUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=200&h=200&q=80',
    description: 'Funksjonell tannpleiesnacks tilsatt havalger og peppermynte for sunne gummer og frisk pust.',
    countryOfOrigin: 'Norge',
    isFeatured: true,
    productCount: 7,
  },
];

// ==========================================
// 2. KATEGORIER (CATEGORIES - GODBIT-FOKUS)
// ==========================================
export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-torket-kjott',
    name: 'Tørket Rent Kjøtt',
    slug: 'torket-kjott',
    description: '100% rene, lufttørkede kjøttgodbiter fra storfe, lam, kylling, elg og and uten fyllstoffer.',
    imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=600&h=400&q=80',
    iconName: 'Beef',
    sortOrder: 1,
    isActive: true,
    seoTitle: 'Tørket rent kjøtt til hund | Hundegodt.no',
    seoDescription: 'Kjøp 100% naturlige lufttørkede kjøttgodbiter. Norskprodusert og kornfritt.',
  },
  {
    id: 'cat-trening',
    name: 'Treningsbiter & Belønning',
    slug: 'trening-og-belonning',
    description: 'Små, myke og uimotståelige belønningsbiter tilpasset klikkertrening, valpekurs og innkalling.',
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=600&h=400&q=80',
    iconName: 'Sparkles',
    sortOrder: 2,
    isActive: true,
    seoTitle: 'Treningsgodbiter til hund | Hundegodt.no',
    seoDescription: 'Smakfulle, fettfrie treningsbiter som ikke smuler i lommen. Perfekt til lydighet og agility.',
  },
  {
    id: 'cat-tyggebein',
    name: 'Tyggebein & Langvarig Kos',
    slug: 'tyggebein-og-kos',
    description: 'Naturlige hjortegevir, elghud-ruller, oksehudsben og luftrør som gir timevis med tyggeglede.',
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=600&h=400&q=80',
    iconName: 'Bone',
    sortOrder: 3,
    isActive: true,
    seoTitle: 'Naturlige tyggebein for hund | Hundegodt.no',
    seoDescription: 'Ubehandlede, slitesterke tyggebein av hjort, elg og okse. 100% uten lim og kjemikalier.',
  },
  {
    id: 'cat-valpegodbiter',
    name: 'Valpegodbiter',
    slug: 'valpegodbiter',
    description: 'Milde, lett-tygde og skånsomme godbiter spesialutviklet for små valpetenner og sensitiv mage.',
    imageUrl: 'https://images.unsplash.com/photo-1591160690555-5debfba289f0?auto=format&fit=crop&w=600&h=400&q=80',
    iconName: 'Smile',
    sortOrder: 4,
    isActive: true,
    seoTitle: 'Myke valpegodbiter | Hundegodt.no',
    seoDescription: 'Skånsomme godbiter til valpetrening og tannfelling. Rike på kalsium og naturlige råvarer.',
  },
  {
    id: 'cat-tannhelse',
    name: 'Tannhelse & Funksjonelt Tygg',
    slug: 'tannhelse-og-funksjonelt',
    description: 'Plakkfjernende tyggestenger, tangsticks og omega-3 snacks som styrker ledd, pels og munnhelse.',
    imageUrl: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?auto=format&fit=crop&w=600&h=400&q=80',
    iconName: 'HeartPulse',
    sortOrder: 5,
    isActive: true,
    seoTitle: 'Tannpleie og funksjonelle godbiter | Hundegodt.no',
    seoDescription: 'Reduser tannstein og dårlig ånde med naturlige tannpleiesticks for hund.',
  },
  {
    id: 'cat-gaveesker',
    name: 'Gaveesker & Godbit-Mix',
    slug: 'gaveesker-og-mix',
    description: 'Luksuriøse godbitbokser, bursdagspakker og Pick & Mix-esker fylt med hundens favoritter.',
    imageUrl: 'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?auto=format&fit=crop&w=600&h=400&q=80',
    iconName: 'Gift',
    sortOrder: 6,
    isActive: true,
    seoTitle: 'Godbitbokser og gavepakker til hund | Hundegodt.no',
    seoDescription: 'Den perfekte gaven til hunden din. Prøv våre populære miksbokser med naturlig snacks.',
  },
];

// ==========================================
// 3. PRODUKTER MED VARIANTER (PRODUCTS - 14 GODBITER)
// ==========================================
export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-okselever',
    brandId: 'b-hundegodt',
    brandName: 'Hundegodt Originals',
    name: 'Naturlig Tørket Norsk Okselever',
    slug: 'naturlig-torket-okselever',
    sku: 'HG-OKS-150',
    barcode: '7090038100121',
    shortDescription: '100% ren, skånsomt lufttørket norsk storfelever. Uimotståelig duft og smak, perfekt for trening.',
    fullDescription: 'Vår bestselgende tørkede okselever lages utelukkende av ferske råvarer fra norske gårder. Leveren er kuttet i passe treningsbiter og langtidstørket ved lav temperatur for å bevare naturlige vitaminer (A, B12 og jern) og den intense kjøttsmaken som selv kresne hunder elsker. Uten korn, fargestoffer eller konserveringsmidler.',
    categoryId: 'cat-torket-kjott',
    categorySlug: 'torket-kjott',
    categoryName: 'Tørket Rent Kjøtt',
    basePriceNok: 129,
    compareAtPriceNok: 159,
    costPriceNok: 48,
    vatRate: 0.25,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    tags: ['Kornfri', '100% Naturlig', 'Norskprodusert', 'Kresne hunder', 'Single Protein'],
    dogSizes: ['mini', 'small', 'medium', 'large', 'giant'],
    dogLifeStages: ['puppy', 'adult', 'senior', 'all'],
    allergens: ['Storfe'],
    ingredients: '100% norsk storfelever. Ingen tilsetningsstoffer.',
    nutritionalInfo: {
      crudeProteinPercent: 64.5,
      crudeFatPercent: 12.2,
      crudeAshPercent: 4.8,
      crudeFiberPercent: 1.1,
    },
    usageGuide: 'Gis som belønning under trening eller kos. Sørg alltid for at hunden har tilgang på friskt drikkevann.',
    rating: 4.9,
    reviewCount: 47,
    viewsCount: 4120,
    cartAddsCount: 940,
    purchaseCount: 712,
    images: [
      {
        id: 'img-okse-1',
        url: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=800&h=800&q=80',
        altText: 'Pose med naturlig tørket okselever for hund',
        sortOrder: 1,
        isPrimary: true,
      },
      {
        id: 'img-okse-2',
        url: 'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?auto=format&fit=crop&w=800&h=800&q=80',
        altText: 'Hund som koser seg med godbit',
        sortOrder: 2,
        isPrimary: false,
      },
    ],
    variants: [
      {
        id: 'var-okse-150g',
        productId: 'prod-okselever',
        title: '150g Pose',
        sku: 'HG-OKS-150',
        barcode: '7090038100121',
        weightGrams: 150,
        priceNok: 129,
        compareAtPriceNok: 159,
        costPriceNok: 48,
        inventoryQuantity: 84,
        lowStockThreshold: 15,
        isActive: true,
      },
      {
        id: 'var-okse-400g',
        productId: 'prod-okselever',
        title: '400g Storpakke',
        sku: 'HG-OKS-400',
        barcode: '7090038100138',
        weightGrams: 400,
        priceNok: 279,
        compareAtPriceNok: 349,
        costPriceNok: 110,
        inventoryQuantity: 38,
        lowStockThreshold: 10,
        isActive: true,
      },
    ],
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-08-20T14:30:00Z',
  },
  {
    id: 'prod-lam-frys',
    brandId: 'b-vom-treats',
    brandName: 'VOM Treats',
    name: 'Frysetørket Norsk Lammekjøtt',
    slug: 'frysetorket-norsk-lammekjott',
    sku: 'VT-LAM-100',
    barcode: '7090045100224',
    shortDescription: 'Ekstremt skånsomt frysetørkede biter av 100% rent norsk lam. Hypoallergent og mykt.',
    fullDescription: 'Frysetørket ferskt lammekjøtt fra norske beiter. Frysetørkingsprosessen fjerner kun fuktighet og bevarer alle næringsstoffer, rå enzymstruktur og den naturlige aromaen. Hypoallergent og spesielt velegnet for hunder med sensitiv mage eller fôrallergi mot kylling og storfe.',
    categoryId: 'cat-torket-kjott',
    categorySlug: 'torket-kjott',
    categoryName: 'Tørket Rent Kjøtt',
    basePriceNok: 149,
    compareAtPriceNok: 179,
    costPriceNok: 60,
    vatRate: 0.25,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    tags: ['Frysetørket', 'Hypoallergen', 'Single Protein', 'Norsk lam'],
    dogSizes: ['mini', 'small', 'medium', 'large', 'giant'],
    dogLifeStages: ['puppy', 'adult', 'senior', 'all'],
    allergens: ['Lam'],
    ingredients: '100% rent norsk lammekjøtt og vom. Ingen tilsetninger.',
    nutritionalInfo: {
      crudeProteinPercent: 58.0,
      crudeFatPercent: 28.0,
      crudeAshPercent: 4.0,
      crudeFiberPercent: 1.0,
    },
    usageGuide: 'Gis som ren belønning eller knuses over tørrfôret som en appetittvekker.',
    rating: 5.0,
    reviewCount: 38,
    viewsCount: 3450,
    cartAddsCount: 780,
    purchaseCount: 590,
    images: [
      {
        id: 'img-lam-1',
        url: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=800&h=800&q=80',
        altText: 'Frysetørket lammekjøtt for hund',
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-lam-100g',
        productId: 'prod-lam-frys',
        title: '100g Pose',
        sku: 'VT-LAM-100',
        barcode: '7090045100224',
        weightGrams: 100,
        priceNok: 149,
        compareAtPriceNok: 179,
        costPriceNok: 60,
        inventoryQuantity: 62,
        lowStockThreshold: 12,
        isActive: true,
      },
      {
        id: 'var-lam-250g',
        productId: 'prod-lam-frys',
        title: '250g Storpakke',
        sku: 'VT-LAM-250',
        barcode: '7090045100231',
        weightGrams: 250,
        priceNok: 299,
        compareAtPriceNok: 369,
        costPriceNok: 125,
        inventoryQuantity: 28,
        lowStockThreshold: 8,
        isActive: true,
      },
    ],
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-08-22T12:00:00Z',
  },
  {
    id: 'prod-elg-blaabaer',
    brandId: 'b-villmark',
    brandName: 'Villmarkssnacks',
    name: 'Treningsbiter med Norsk Elg & Skogsblåbær',
    slug: 'treningsbiter-elg-blaabaer',
    sku: 'VM-ELG-120',
    barcode: '7090056100335',
    shortDescription: 'Halvmyke belønningsbiter med 85% ferskt elgkjøtt og antioksidantrike ville blåbær.',
    fullDescription: 'Perfekte treningsbiter for lydighetstrening, agility og tur! Laget av ekte norsk elgkjøtt fra lokale jaktlag i Trøndelag, blandet med ville blåbær rike på naturlige antioksidanter. Bitene er myke nok til å deles raskt, og smuler ikke i lommen eller godbitvesken.',
    categoryId: 'cat-trening',
    categorySlug: 'trening-og-belonning',
    categoryName: 'Treningsbiter & Belønning',
    basePriceNok: 119,
    compareAtPriceNok: 139,
    costPriceNok: 42,
    vatRate: 0.25,
    isActive: true,
    isFeatured: true,
    isNew: true,
    isBestseller: true,
    tags: ['Halvmyke', 'Elgkjøtt', 'Supermat', 'Kladdfri i lommen', 'Norsk vilt'],
    dogSizes: ['mini', 'small', 'medium', 'large', 'giant'],
    dogLifeStages: ['puppy', 'adult', 'senior', 'all'],
    allergens: ['Elg'],
    ingredients: '85% ferskt elgkjøtt, 10% skogsblåbær, vegetabilsk glyserol, mineraler.',
    nutritionalInfo: {
      crudeProteinPercent: 44.0,
      crudeFatPercent: 14.5,
      crudeAshPercent: 5.2,
      crudeFiberPercent: 2.1,
    },
    usageGuide: 'Gis under treningsøkter som hurtig belønning. Svært motiverende!',
    rating: 4.95,
    reviewCount: 52,
    viewsCount: 4890,
    cartAddsCount: 1120,
    purchaseCount: 880,
    images: [
      {
        id: 'img-elg-1',
        url: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&h=800&q=80',
        altText: 'Pose med treningsbiter av elg og blåbær',
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-elg-120g',
        productId: 'prod-elg-blaabaer',
        title: '120g Pose',
        sku: 'VM-ELG-120',
        barcode: '7090056100335',
        weightGrams: 120,
        priceNok: 119,
        compareAtPriceNok: 139,
        costPriceNok: 42,
        inventoryQuantity: 95,
        lowStockThreshold: 20,
        isActive: true,
      },
      {
        id: 'var-elg-300g',
        productId: 'prod-elg-blaabaer',
        title: '300g Storpakke',
        sku: 'VM-ELG-300',
        barcode: '7090056100342',
        weightGrams: 300,
        priceNok: 249,
        compareAtPriceNok: 299,
        costPriceNok: 90,
        inventoryQuantity: 45,
        lowStockThreshold: 10,
        isActive: true,
      },
    ],
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-08-24T09:00:00Z',
  },
  {
    id: 'prod-hjortegevir',
    brandId: 'b-nordic-chew',
    brandName: 'Nordic Chew Co.',
    name: 'Norsk Hjortegevir — Naturlig Tyggekos',
    slug: 'norsk-hjortegevir-tyggekos',
    sku: 'NC-GEV-M',
    barcode: '7090078100441',
    shortDescription: '100% naturlig felt gevir fra norske hjorter. Langvarig, luktfritt og fullt av mineraler.',
    fullDescription: 'Hjortegevir er naturens eget tannbørste og kanskje verdens mest holdbare tyggebein! Gevirene felles naturlig av ville hjorter i de vestlandske fjellene og samles skånsomt inn for hånd. De kutter ikke opp tannkjøttet og gir fra seg lite lukt og søl.',
    categoryId: 'cat-tyggebein',
    categorySlug: 'tyggebein-og-kos',
    categoryName: 'Tyggebein & Langvarig Kos',
    basePriceNok: 169,
    costPriceNok: 65,
    vatRate: 0.25,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    tags: ['Luktfritt', 'Ekstremt holdbart', 'Tannrens', '100% Naturlig', 'Hjort'],
    dogSizes: ['small', 'medium', 'large', 'giant'],
    dogLifeStages: ['adult', 'senior', 'all'],
    allergens: ['Hjort'],
    ingredients: '100% naturlig felt hjortegevir.',
    nutritionalInfo: {
      crudeProteinPercent: 38.0,
      crudeFatPercent: 0.2,
      crudeAshPercent: 52.0,
      crudeFiberPercent: 1.0,
    },
    usageGuide: 'Supervisér alltid hunden under tygging. Ta bort geviret dersom det blir lite nok til å svelges.',
    rating: 4.85,
    reviewCount: 41,
    viewsCount: 3120,
    cartAddsCount: 650,
    purchaseCount: 490,
    images: [
      {
        id: 'img-gev-1',
        url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&h=800&q=80',
        altText: 'Naturlig hjortegevir for hund',
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-gev-s',
        productId: 'prod-hjortegevir',
        title: 'Small (Hunder 3-10 kg)',
        sku: 'NC-GEV-S',
        barcode: '7090078100434',
        weightGrams: 75,
        priceNok: 129,
        costPriceNok: 48,
        inventoryQuantity: 35,
        lowStockThreshold: 10,
        isActive: true,
      },
      {
        id: 'var-gev-m',
        productId: 'prod-hjortegevir',
        title: 'Medium (Hunder 10-25 kg)',
        sku: 'NC-GEV-M',
        barcode: '7090078100441',
        weightGrams: 150,
        priceNok: 189,
        costPriceNok: 75,
        inventoryQuantity: 42,
        lowStockThreshold: 10,
        isActive: true,
      },
      {
        id: 'var-gev-l',
        productId: 'prod-hjortegevir',
        title: 'Large (Hunder 25+ kg)',
        sku: 'NC-GEV-L',
        barcode: '7090078100458',
        weightGrams: 250,
        priceNok: 269,
        costPriceNok: 110,
        inventoryQuantity: 24,
        lowStockThreshold: 5,
        isActive: true,
      },
    ],
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-08-21T11:00:00Z',
  },
  {
    id: 'prod-kyllingnakker',
    brandId: 'b-hundegodt',
    brandName: 'Hundegodt Originals',
    name: 'Sprø Lufttørkede Kyllingnakker',
    slug: 'spro-torkede-kyllingnakker',
    sku: 'HG-KYL-200',
    barcode: '7090038100552',
    shortDescription: '100% norske kyllingnakker, langtidstørket til sprø perfeksjon. Rikt på naturlig kalsium.',
    fullDescription: 'Norsk kylling fra Jæren, skånsomt tørket med naturlig varmluft. Kyllingnakkene gir en herlig knasende tyggeopplevelse som skånsomt renser tennene for matrester og stimulerer tannkjøttet. Helt fri for korn, salt og kunstige tilsetningsstoffer.',
    categoryId: 'cat-torket-kjott',
    categorySlug: 'torket-kjott',
    categoryName: 'Tørket Rent Kjøtt',
    basePriceNok: 99,
    compareAtPriceNok: 129,
    costPriceNok: 35,
    vatRate: 0.25,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    tags: ['Kalsiumrik', 'Naturlig tannrens', 'Norsk kylling', 'Knasende god'],
    dogSizes: ['mini', 'small', 'medium', 'large', 'giant'],
    dogLifeStages: ['puppy', 'adult', 'senior', 'all'],
    allergens: ['Kylling'],
    ingredients: '100% norsk kyllingnakke. Tørket.',
    nutritionalInfo: {
      crudeProteinPercent: 52.0,
      crudeFatPercent: 22.4,
      crudeAshPercent: 14.8,
      crudeFiberPercent: 0.8,
    },
    usageGuide: 'Gis som kos eller et lett tygg mellom måltidene.',
    rating: 4.8,
    reviewCount: 29,
    viewsCount: 2210,
    cartAddsCount: 480,
    purchaseCount: 360,
    images: [
      {
        id: 'img-nakke-1',
        url: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=800&h=800&q=80',
        altText: 'Tørkede kyllingnakker for hund',
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-nakke-200g',
        productId: 'prod-kyllingnakker',
        title: '200g Pose',
        sku: 'HG-KYL-200',
        barcode: '7090038100552',
        weightGrams: 200,
        priceNok: 99,
        compareAtPriceNok: 129,
        costPriceNok: 35,
        inventoryQuantity: 70,
        lowStockThreshold: 15,
        isActive: true,
      },
      {
        id: 'var-nakke-500g',
        productId: 'prod-kyllingnakker',
        title: '500g Storpakke',
        sku: 'HG-KYL-500',
        barcode: '7090038100569',
        weightGrams: 500,
        priceNok: 199,
        compareAtPriceNok: 249,
        costPriceNok: 75,
        inventoryQuantity: 32,
        lowStockThreshold: 8,
        isActive: true,
      },
    ],
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-08-19T10:00:00Z',
  },
  {
    id: 'prod-kaninoerer',
    brandId: 'b-hundegodt',
    brandName: 'Hundegodt Originals',
    name: 'Tørkede Kaninører med Pels',
    slug: 'torkede-kaninoerer-med-pels',
    sku: 'HG-KAN-100',
    barcode: '7090038100668',
    shortDescription: '100% naturlige kaninører med pels. Skånsom fordøyelse, naturlig fiber og parasittrens.',
    fullDescription: 'Kaninører med pels er en fantastisk naturlig godbit som støtter hundens tarmhelse. Pelsen fungerer som en skånsom børste gjennom fordøyelseskanalen og bidrar til naturlig fjerning av slaggstoffer og ormeegg. Svært magert og hypoallergent.',
    categoryId: 'cat-tyggebein',
    categorySlug: 'tyggebein-og-kos',
    categoryName: 'Tyggebein & Langvarig Kos',
    basePriceNok: 139,
    compareAtPriceNok: 169,
    costPriceNok: 52,
    vatRate: 0.25,
    isActive: true,
    isFeatured: false,
    isNew: true,
    isBestseller: true,
    tags: ['Med pels', 'Tarmhelse', 'Hypoallergen', 'Mager'],
    dogSizes: ['mini', 'small', 'medium', 'large', 'giant'],
    dogLifeStages: ['puppy', 'adult', 'senior', 'all'],
    allergens: ['Kanin'],
    ingredients: '100% tørket kaninøre med pels.',
    nutritionalInfo: {
      crudeProteinPercent: 65.0,
      crudeFatPercent: 12.0,
      crudeAshPercent: 3.5,
      crudeFiberPercent: 4.5,
    },
    usageGuide: 'Gis 2-3 ganger i uken som et sunt fordøyelsessupplement og tygg.',
    rating: 4.9,
    reviewCount: 34,
    viewsCount: 2980,
    cartAddsCount: 620,
    purchaseCount: 460,
    images: [
      {
        id: 'img-kanin-1',
        url: 'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?auto=format&fit=crop&w=800&h=800&q=80',
        altText: 'Kaninører med pels for hund',
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-kanin-100g',
        productId: 'prod-kaninoerer',
        title: '100g Pose (ca. 8-10 stk)',
        sku: 'HG-KAN-100',
        barcode: '7090038100668',
        weightGrams: 100,
        priceNok: 139,
        compareAtPriceNok: 169,
        costPriceNok: 52,
        inventoryQuantity: 55,
        lowStockThreshold: 12,
        isActive: true,
      },
    ],
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-08-23T15:00:00Z',
  },
  {
    id: 'prod-gullboks',
    brandId: 'b-hundegodt',
    brandName: 'Hundegodt Originals',
    name: 'Hundegodt Gull-Boks: Luksus Godbitmix',
    slug: 'hundegodt-gull-boks-luksus-mix',
    sku: 'HG-BOX-GOLD',
    barcode: '7090038100774',
    shortDescription: 'Eksklusiv gaveeske fylt med 5 av våre mest populære poser med tørket norsk kjøtt og snacks.',
    fullDescription: 'Den ultimate gaven til din egen hund eller en firbent venn! Gull-Boksen inneholder 5 fullstendige poser av våre bestselgere: Tørket okselever (150g), Frysetørket lam (100g), Treningsbiter med elg (120g), Kyllingnakker (200g) og Tannpleiesticks (150g). Pakket i en vakker, resirkulerbar gaveeske.',
    categoryId: 'cat-gaveesker',
    categorySlug: 'gaveesker-og-mix',
    categoryName: 'Gaveesker & Godbit-Mix',
    basePriceNok: 499,
    compareAtPriceNok: 649,
    costPriceNok: 195,
    vatRate: 0.25,
    isActive: true,
    isFeatured: true,
    isNew: true,
    isBestseller: true,
    tags: ['Gaveeske', 'Bursdag', 'Mest for pengene', '5 bestselgere'],
    dogSizes: ['mini', 'small', 'medium', 'large', 'giant'],
    dogLifeStages: ['puppy', 'adult', 'senior', 'all'],
    allergens: ['Storfe', 'Lam', 'Kylling', 'Elg'],
    ingredients: 'Blanding av 100% tørket storfe, lam, elg, kylling og tang.',
    nutritionalInfo: {
      crudeProteinPercent: 60.0,
      crudeFatPercent: 16.0,
      crudeAshPercent: 6.0,
      crudeFiberPercent: 1.5,
    },
    usageGuide: 'Nyt et variert utvalg av godbiter og tygg gjennom hele måneden.',
    rating: 5.0,
    reviewCount: 65,
    viewsCount: 5600,
    cartAddsCount: 1250,
    purchaseCount: 940,
    images: [
      {
        id: 'img-box-1',
        url: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=800&h=800&q=80',
        altText: 'Luksus godbitboks for hund',
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-box-standard',
        productId: 'prod-gullboks',
        title: 'Komplett Gull-Boks (5 poser)',
        sku: 'HG-BOX-GOLD',
        barcode: '7090038100774',
        weightGrams: 720,
        priceNok: 499,
        compareAtPriceNok: 649,
        costPriceNok: 195,
        inventoryQuantity: 40,
        lowStockThreshold: 10,
        isActive: true,
      },
    ],
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-08-25T16:00:00Z',
  },
  {
    id: 'prod-valpegodbiter',
    brandId: 'b-potekjokkenet',
    brandName: 'PoteKjøkkenet',
    name: 'Myke Valpegodbiter med Kylling & Geitemelk',
    slug: 'myke-valpegodbiter-kylling-geitemelk',
    sku: 'PK-VALP-100',
    barcode: '7090089100881',
    shortDescription: 'Supermilde, myke godbiter med norsk kyllingfilet og næringsrik geitemelk. Skånsom for magen.',
    fullDescription: 'Spesialbakt for de minste valpene! Med ekte norsk kyllingkjøtt og skånsom geitemelk som minner om morsmelken. De myke små putene er lette å tygge for sarte melketenner og beriket med kalsium og vitaminer for sunn vekst.',
    categoryId: 'cat-valpegodbiter',
    categorySlug: 'valpegodbiter',
    categoryName: 'Valpegodbiter',
    basePriceNok: 109,
    compareAtPriceNok: 139,
    costPriceNok: 38,
    vatRate: 0.25,
    isActive: true,
    isFeatured: true,
    isNew: true,
    isBestseller: true,
    tags: ['Valp', 'Geitemelk', 'Myke biter', 'Skånsom mage', 'Valpekurs'],
    dogSizes: ['mini', 'small', 'medium', 'large', 'giant'],
    dogLifeStages: ['puppy'],
    allergens: ['Kylling', 'Melk'],
    ingredients: '75% fersk norsk kylling, 15% geitemelk, potetstivelse, mineraler.',
    nutritionalInfo: {
      crudeProteinPercent: 36.0,
      crudeFatPercent: 12.0,
      crudeAshPercent: 4.2,
      crudeFiberPercent: 1.0,
    },
    usageGuide: 'Perfekt som belønning under stuerent-trening, innkalling og sosialisering.',
    rating: 4.95,
    reviewCount: 39,
    viewsCount: 3700,
    cartAddsCount: 840,
    purchaseCount: 620,
    images: [
      {
        id: 'img-valp-1',
        url: 'https://images.unsplash.com/photo-1591160690555-5debfba289f0?auto=format&fit=crop&w=800&h=800&q=80',
        altText: 'Valpegodbiter pose',
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-valp-100g',
        productId: 'prod-valpegodbiter',
        title: '100g Pose',
        sku: 'PK-VALP-100',
        barcode: '7090089100881',
        weightGrams: 100,
        priceNok: 109,
        compareAtPriceNok: 139,
        costPriceNok: 38,
        inventoryQuantity: 65,
        lowStockThreshold: 15,
        isActive: true,
      },
    ],
    createdAt: '2026-04-01T10:00:00Z',
    updatedAt: '2026-08-25T11:00:00Z',
  },
  {
    id: 'prod-tannpleiesticks',
    brandId: 'b-dentalbite',
    brandName: 'DentalBite Nordic',
    name: 'Tannpleiesticks med Norsk Tang & Peppermynte',
    slug: 'tannpleiesticks-norsk-tang-mynte',
    sku: 'DB-DENT-7PK',
    barcode: '7090099100998',
    shortDescription: '100% vegetabilske tyggestenger med norsk kysttang (Ascophyllum Nodosum) og frisk mynte.',
    fullDescription: 'Dokumentert effekt mot tannstein og belegg! Inneholder bærekraftig innhøstet norsk grisetang som via spyttet motvirker plakkdannelse. Den riflede formen masserer tannkjøttet mens hunden tygger, og mynten sikrer frisk og behagelig hundeånde.',
    categoryId: 'cat-tannhelse',
    categorySlug: 'tannhelse-og-funksjonelt',
    categoryName: 'Tannhelse & Funksjonelt Tygg',
    basePriceNok: 119,
    compareAtPriceNok: 149,
    costPriceNok: 40,
    vatRate: 0.25,
    isActive: true,
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    tags: ['Tannrens', 'Frisk pust', 'Norsk tang', 'Kornfri', 'Vegetabilsk'],
    dogSizes: ['mini', 'small', 'medium', 'large', 'giant'],
    dogLifeStages: ['adult', 'senior', 'all'],
    allergens: [],
    ingredients: 'Potetfiber, vegetabilsk glyserin, norsk grisetang (Ascophyllum Nodosum), peppermynteolje, klorofyll.',
    nutritionalInfo: {
      crudeProteinPercent: 8.5,
      crudeFatPercent: 2.2,
      crudeAshPercent: 4.0,
      crudeFiberPercent: 6.5,
    },
    usageGuide: 'Gis 1 stick daglig etter kveldsturen for optimal munnhelse.',
    rating: 4.88,
    reviewCount: 56,
    viewsCount: 4200,
    cartAddsCount: 910,
    purchaseCount: 710,
    images: [
      {
        id: 'img-dent-1',
        url: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?auto=format&fit=crop&w=800&h=800&q=80',
        altText: 'Tannpleiesticks for hund',
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-dent-7pk',
        productId: 'prod-tannpleiesticks',
        title: '7 stk Pakke (1 uke)',
        sku: 'DB-DENT-7PK',
        barcode: '7090099100998',
        weightGrams: 180,
        priceNok: 119,
        compareAtPriceNok: 149,
        costPriceNok: 40,
        inventoryQuantity: 88,
        lowStockThreshold: 20,
        isActive: true,
      },
      {
        id: 'var-dent-28pk',
        productId: 'prod-tannpleiesticks',
        title: '28 stk Månedspakke',
        sku: 'DB-DENT-28PK',
        barcode: '7090099101001',
        weightGrams: 720,
        priceNok: 389,
        compareAtPriceNok: 476,
        costPriceNok: 135,
        inventoryQuantity: 34,
        lowStockThreshold: 10,
        isActive: true,
      },
    ],
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-08-25T14:00:00Z',
  },
  {
    id: 'prod-laksekuler',
    brandId: 'b-potekjokkenet',
    brandName: 'PoteKjøkkenet',
    name: 'Sprø Villaks-Kuler med Omega-3',
    slug: 'spro-villaks-kuler-omega-3',
    sku: 'PK-LAK-150',
    barcode: '7090089101116',
    shortDescription: 'Knasende godbiter av 100% fersk norsk laks. Gir silkemyk pels og sterke klør.',
    fullDescription: 'Bakt med ren fersk laks fra norskekysten. Laksen er naturlig rik på de essensielle fettsyrene EPA og DHA som styrker hudbarrieren, reduserer røyting og gir en glansfull pels. En fantastisk smaksopplevelse som hunden vil logre hemningsløst etter.',
    categoryId: 'cat-tannhelse',
    categorySlug: 'tannhelse-og-funksjonelt',
    categoryName: 'Tannhelse & Funksjonelt Tygg',
    basePriceNok: 129,
    compareAtPriceNok: 159,
    costPriceNok: 45,
    vatRate: 0.25,
    isActive: true,
    isFeatured: false,
    isNew: false,
    isBestseller: true,
    tags: ['Omega-3', 'Blank pels', 'Norsk laks', 'Kornfri'],
    dogSizes: ['mini', 'small', 'medium', 'large', 'giant'],
    dogLifeStages: ['puppy', 'adult', 'senior', 'all'],
    allergens: ['Laks'],
    ingredients: '100% norsk laks.',
    nutritionalInfo: {
      crudeProteinPercent: 62.0,
      crudeFatPercent: 24.0,
      crudeAshPercent: 5.0,
      crudeFiberPercent: 0.5,
    },
    usageGuide: 'Gis som kos eller som et daglig tilskudd for pels og ledd.',
    rating: 4.9,
    reviewCount: 44,
    viewsCount: 3100,
    cartAddsCount: 670,
    purchaseCount: 510,
    images: [
      {
        id: 'img-laks-1',
        url: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=800&h=800&q=80',
        altText: 'Laksegodbiter for hund',
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-laks-150g',
        productId: 'prod-laksekuler',
        title: '150g Pose',
        sku: 'PK-LAK-150',
        barcode: '7090089101116',
        weightGrams: 150,
        priceNok: 129,
        compareAtPriceNok: 159,
        costPriceNok: 45,
        inventoryQuantity: 58,
        lowStockThreshold: 12,
        isActive: true,
      },
    ],
    createdAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-08-22T10:00:00Z',
  },
];

// ==========================================
// 4. KUNDEKONTI (CUSTOMER PROFILES)
// ==========================================
export const INITIAL_CUSTOMERS: CustomerProfile[] = [
  {
    id: 'cust-emma',
    firstName: 'Emma',
    lastName: 'Johansen',
    email: 'emma.johansen@example.no',
    phone: '+47 987 65 432',
    addresses: [
      {
        id: 'addr-1',
        type: 'shipping',
        fullName: 'Emma Johansen',
        streetAddress: 'Ullevålsveien 42',
        postalCode: '0167',
        city: 'Oslo',
        country: 'Norge',
        phone: '+47 987 65 432',
        isDefault: true,
      },
    ],
    dogs: [
      {
        id: 'dog-milo',
        name: 'Milo',
        breed: 'Golden Retriever',
        birthDate: '2025-06-15',
        weightKg: 14.5,
        size: 'medium',
        lifeStage: 'puppy',
        gender: 'male',
        activityLevel: 'high',
        allergies: ['Kylling'],
        sensitivities: ['Sensitiv mage'],
        favoriteFlavors: ['Okselever', 'Elg', 'Lam'],
        createdAt: '2026-01-12T14:30:00Z',
      },
    ],
    totalSpendNok: 2450,
    orderCount: 5,
    acceptsMarketing: true,
    createdAt: '2026-01-12T14:30:00Z',
  },
  {
    id: 'cust-thomas',
    firstName: 'Thomas',
    lastName: 'Berg',
    email: 'thomas.berg@example.no',
    phone: '+47 412 34 567',
    addresses: [
      {
        id: 'addr-2',
        type: 'shipping',
        fullName: 'Thomas Berg',
        streetAddress: 'Fjellveien 12',
        postalCode: '5014',
        city: 'Bergen',
        country: 'Norge',
        phone: '+47 412 34 567',
        isDefault: true,
      },
    ],
    dogs: [
      {
        id: 'dog-atlas',
        name: 'Atlas',
        breed: 'Sibirsk Husky',
        birthDate: '2023-04-10',
        weightKg: 27.0,
        size: 'large',
        lifeStage: 'adult',
        gender: 'male',
        activityLevel: 'working',
        allergies: [],
        sensitivities: [],
        favoriteFlavors: ['Hjortegevir', 'Okselever', 'Lammekjøtt'],
        createdAt: '2026-01-05T09:15:00Z',
      },
    ],
    totalSpendNok: 4890,
    orderCount: 8,
    acceptsMarketing: true,
    createdAt: '2026-01-05T09:15:00Z',
  },
];

// ==========================================
// 5. ORDRER (ORDERS)
// ==========================================
export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-10482',
    orderNumber: 'HG-10482',
    customerId: 'cust-emma',
    customerName: 'Emma Johansen',
    customerEmail: 'emma.johansen@example.no',
    customerPhone: '+47 987 65 432',
    shippingAddress: {
      id: 'addr-ord-1',
      type: 'shipping',
      fullName: 'Emma Johansen',
      streetAddress: 'Ullevålsveien 42',
      postalCode: '0167',
      city: 'Oslo',
      country: 'Norge',
      phone: '+47 987 65 432',
      isDefault: true,
    },
    items: [
      {
        id: 'oi-1',
        productId: 'prod-okselever',
        variantId: 'var-okse-150g',
        productName: 'Naturlig Tørket Norsk Okselever',
        variantTitle: '150g Pose',
        sku: 'HG-OKS-150',
        unitPriceNok: 129,
        quantity: 2,
        totalPriceNok: 258,
        imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=300&h=300&q=80',
        vatAmountNok: 51.6,
      },
      {
        id: 'oi-2',
        productId: 'prod-elg-blaabaer',
        variantId: 'var-elg-120g',
        productName: 'Treningsbiter med Norsk Elg & Skogsblåbær',
        variantTitle: '120g Pose',
        sku: 'VM-ELG-120',
        unitPriceNok: 119,
        quantity: 2,
        totalPriceNok: 238,
        imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=300&h=300&q=80',
        vatAmountNok: 47.6,
      },
      {
        id: 'oi-3',
        productId: 'prod-gullboks',
        variantId: 'var-box-standard',
        productName: 'Hundegodt Gull-Boks: Luksus Godbitmix',
        variantTitle: 'Komplett Gull-Boks (5 poser)',
        sku: 'HG-BOX-GOLD',
        unitPriceNok: 499,
        quantity: 1,
        totalPriceNok: 499,
        imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=300&h=300&q=80',
        vatAmountNok: 99.8,
      },
    ],
    subtotalNok: 995,
    discountNok: 99.5,
    shippingNok: 0,
    vatNok: 179.1,
    totalNok: 895.5,
    status: 'processing',
    paymentProvider: 'vipps',
    paymentStatus: 'captured',
    shippingCarrier: 'bring',
    shippingMethodName: 'Bring Pakke til Hentested',
    trackingNumber: '370720124891992041NO',
    createdAt: '2026-08-26T09:30:00Z',
    updatedAt: '2026-08-26T09:35:00Z',
  },
  {
    id: 'ord-10481',
    orderNumber: 'HG-10481',
    customerId: 'cust-thomas',
    customerName: 'Thomas Berg',
    customerEmail: 'thomas.berg@example.no',
    customerPhone: '+47 412 34 567',
    shippingAddress: {
      id: 'addr-ord-2',
      type: 'shipping',
      fullName: 'Thomas Berg',
      streetAddress: 'Fjellveien 12',
      postalCode: '5014',
      city: 'Bergen',
      country: 'Norge',
      phone: '+47 412 34 567',
      isDefault: true,
    },
    items: [
      {
        id: 'oi-4',
        productId: 'prod-hjortegevir',
        variantId: 'var-gev-l',
        productName: 'Norsk Hjortegevir — Naturlig Tyggekos',
        variantTitle: 'Large (Hunder 25+ kg)',
        sku: 'NC-GEV-L',
        unitPriceNok: 269,
        quantity: 2,
        totalPriceNok: 538,
        imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=300&h=300&q=80',
        vatAmountNok: 107.6,
      },
      {
        id: 'oi-5',
        productId: 'prod-lam-frys',
        variantId: 'var-lam-250g',
        productName: 'Frysetørket Norsk Lammekjøtt',
        variantTitle: '250g Storpakke',
        sku: 'VT-LAM-250',
        unitPriceNok: 299,
        quantity: 1,
        totalPriceNok: 299,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=300&h=300&q=80',
        vatAmountNok: 59.8,
      },
    ],
    subtotalNok: 837,
    discountNok: 0,
    shippingNok: 0,
    vatNok: 167.4,
    totalNok: 837,
    status: 'shipped',
    paymentProvider: 'klarna',
    paymentStatus: 'captured',
    shippingCarrier: 'bring',
    shippingMethodName: 'Bring Pakke til Hentested',
    trackingNumber: '370720124891991234NO',
    createdAt: '2026-08-24T14:15:00Z',
    updatedAt: '2026-08-24T16:45:00Z',
  },
];

// ==========================================
// 6. KAMPANJER & RABATTKODER
// ==========================================
export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-godbit-fest',
    name: 'Godbit-Uken: 20% på alle treningsbiter & tygg',
    slug: 'godbit-uken',
    description: 'Fyll opp godbitposen med 100% naturlige norske godbiter! Gjelder alle treningsbiter og tyggebein.',
    type: 'percentage',
    value: 20,
    minOrderAmountNok: 300,
    appliesTo: 'category',
    targetIds: ['cat-trening', 'cat-tyggebein'],
    startDate: '2026-08-01T00:00:00Z',
    endDate: '2026-09-30T23:59:59Z',
    isActive: true,
    bannerHeadline: '🐾 GODBIT-UKEN: 20% RABATT PÅ ALLE TRENINGSBITER OG NATURLIG TYGG!',
    bannerCtaText: 'Utforsk tilbud',
    bannerCtaLink: '/produkter?kategori=trening-og-belonning',
    priority: 1,
    timesUsed: 142,
    revenueGeneratedNok: 85200,
  },
  {
    id: 'camp-gullboks-bundle',
    name: 'Gull-Boks Kampanje: 15% rabatt på gaveesker',
    slug: 'gullboks-kampanje',
    description: 'Kjøp vår populære Luksus Godbitmix og få 15% rabatt + gratis Bring-frakt.',
    type: 'percentage',
    value: 15,
    minOrderAmountNok: 400,
    appliesTo: 'category',
    targetIds: ['cat-gaveesker'],
    startDate: '2026-08-10T00:00:00Z',
    endDate: '2026-09-15T23:59:59Z',
    isActive: true,
    bannerHeadline: '✨ LUKSUS GODBITMIX: SPAR 15% VED KJØP AV GAVEBOKSER!',
    bannerCtaText: 'Se gaveesker',
    bannerCtaLink: '/produkter?kategori=gaveesker-og-mix',
    priority: 2,
    timesUsed: 65,
    revenueGeneratedNok: 32435,
  },
];

export const INITIAL_DISCOUNT_CODES: DiscountCode[] = [
  {
    id: 'dc-1',
    code: 'GODT15',
    type: 'percentage',
    value: 15,
    minOrderAmountNok: 300,
    maxUses: 500,
    currentUses: 142,
    onlyNewCustomers: true,
    oncePerCustomer: true,
    startDate: '2026-01-01T00:00:00Z',
    endDate: '2026-12-31T23:59:59Z',
    isActive: true,
    totalDiscountGivenNok: 6390,
    totalOrderValueGeneratedNok: 42600,
  },
  {
    id: 'dc-2',
    code: 'VALPEKOS',
    type: 'percentage',
    value: 20,
    minOrderAmountNok: 250,
    maxUses: 300,
    currentUses: 88,
    onlyNewCustomers: false,
    oncePerCustomer: true,
    startDate: '2026-01-01T00:00:00Z',
    endDate: '2026-12-31T23:59:59Z',
    isActive: true,
    totalDiscountGivenNok: 4400,
    totalOrderValueGeneratedNok: 22000,
  },
  {
    id: 'dc-3',
    code: 'FRIFRAKT',
    type: 'free_shipping',
    value: 79,
    minOrderAmountNok: 400,
    maxUses: 1000,
    currentUses: 412,
    onlyNewCustomers: false,
    oncePerCustomer: false,
    startDate: '2026-01-01T00:00:00Z',
    endDate: '2026-12-31T23:59:59Z',
    isActive: true,
    totalDiscountGivenNok: 32548,
    totalOrderValueGeneratedNok: 247200,
  },
];

// ==========================================
// 7. ANMELDELSER (REVIEWS)
// ==========================================
export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-okselever',
    productName: 'Naturlig Tørket Norsk Okselever',
    customerId: 'cust-emma',
    customerName: 'Emma J.',
    dogName: 'Milo',
    dogBreed: 'Golden Retriever (Valp)',
    rating: 5,
    title: 'Helt fantastisk belønning!',
    comment: 'Milo gjør hva som helst for disse bitene. Perfekt størrelse for valpetrening og herlig at det er 100% rent norsk kjøtt uten tilsetninger.',
    verifiedPurchase: true,
    status: 'approved',
    adminResponse: 'Tusen takk Emma! Så fantastisk å høre at Milo er motivert på valpekurset 🐾',
    createdAt: '2026-08-15T12:00:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-elg-blaabaer',
    productName: 'Treningsbiter med Norsk Elg & Skogsblåbær',
    customerId: 'cust-thomas',
    customerName: 'Thomas B.',
    dogName: 'Atlas',
    dogBreed: 'Sibirsk Husky',
    rating: 5,
    title: 'Kladdfrie og utrolig populære!',
    comment: 'Disse bitene smuler ikke i lommen under lange fjellturer, og Atlas har en lynrask innkalling så snart han kjenner duften av elgkjøtt.',
    verifiedPurchase: true,
    status: 'approved',
    createdAt: '2026-08-18T16:30:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-hjortegevir',
    productName: 'Norsk Hjortegevir — Naturlig Tyggekos',
    customerId: 'cust-kari',
    customerName: 'Kari N.',
    dogName: 'Bella',
    dogBreed: 'Fransk Bulldog',
    rating: 5,
    title: 'Varer i ukevis uten lukt!',
    comment: 'Det eneste tyggebeinet som ikke blir slimete eller lukter vondt i stuen. Bella koser seg med dette hver kveld.',
    verifiedPurchase: true,
    status: 'approved',
    createdAt: '2026-08-22T19:00:00Z',
  },
];

// ==========================================
// 8. CMS FORSIDEBLOKKER (CMS BLOCKS - GODBIT-FOKUS)
// ==========================================
export const INITIAL_HERO: CmsHeroBlock = {
  id: 'hero-main-1',
  badgeText: '🐾 100% Naturlige Norske Hundegodbiter & Tygg',
  heading: 'Norges reneste godbiter servert i hver eneste skål.',
  subheading: '100% naturlige råvarer, skånsomt lufttørket norsk kjøtt og uimotståelige treningsbiter. Helt uten korn, sukker eller kjemiske tilsetningsstoffer.',
  primaryCtaText: 'Utforsk godbiter',
  primaryCtaLink: '/produkter',
  secondaryCtaText: 'Finn riktig tygg',
  secondaryCtaLink: '/guider',
  imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&h=800&q=80',
  isActive: true,
};

export const INITIAL_CMS_SECTIONS: CmsSectionBlock[] = [
  {
    id: 'sec-hero',
    type: 'hero',
    title: 'Hovedbanner / Hero',
    sortOrder: 1,
    isEnabled: true,
  },
  {
    id: 'sec-popular',
    type: 'popular_now',
    title: 'Mest populære godbiter akkurat nå',
    subtitle: 'Våre bestselgende godbiter og naturlige tyggebein',
    sortOrder: 2,
    isEnabled: true,
  },
  {
    id: 'sec-puppy',
    type: 'puppy_focus',
    title: 'Skånsomme godbiter for valpen',
    subtitle: 'Milde, myke godbiter med geitemelk og lettfordøyelig kylling',
    sortOrder: 3,
    isEnabled: true,
  },
  {
    id: 'sec-activity',
    type: 'activity_and_play',
    title: 'Treningsbiter for innkalling og lydighet',
    subtitle: 'Fettfrie og kladdfrie godbiter som ikke smuler i lommen',
    sortOrder: 4,
    isEnabled: true,
  },
  {
    id: 'sec-snacks',
    type: 'snacks_and_treats',
    title: '100% Lufttørket Rent Kjøtt',
    subtitle: 'Uten fyllstoffer, fargestoffer eller kjemisk bindemiddel',
    sortOrder: 5,
    isEnabled: true,
  },
  {
    id: 'sec-brands',
    type: 'featured_brands',
    title: 'Norske & Nordiske Produsenter',
    subtitle: 'Kvalitet fra produsenter med kjærlighet for rene råvarer',
    sortOrder: 6,
    isEnabled: true,
  },
  {
    id: 'sec-reviews',
    type: 'customer_reviews',
    title: 'Hva andre hundeeiere sier',
    subtitle: 'Over 10 000 logrende haler over hele Norge',
    sortOrder: 7,
    isEnabled: true,
  },
  {
    id: 'sec-newsletter',
    type: 'newsletter_signup',
    title: 'Få 15% rabatt på din første godbitbestilling',
    subtitle: 'Meld deg på nyhetsbrevet for sunne godbittips og eksklusive tilbud.',
    sortOrder: 8,
    isEnabled: true,
  },
];

// ==========================================
// 9. FORLATTE HANDLEKURVER (ABANDONED CARTS)
// ==========================================
export const INITIAL_ABANDONED_CARTS: AbandonedCart[] = [
  {
    id: 'ac-1',
    customerEmail: 'sander.lie@example.no',
    customerName: 'Sander Lie',
    items: [
      {
        productId: 'prod-gullboks',
        variantId: 'var-box-standard',
        productName: 'Hundegodt Gull-Boks: Luksus Godbitmix',
        variantTitle: 'Komplett Gull-Boks (5 poser)',
        brandName: 'Hundegodt Originals',
        imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=300&h=300&q=80',
        priceNok: 499,
        compareAtPriceNok: 649,
        quantity: 1,
        maxInventory: 40,
        slug: 'hundegodt-gull-boks-luksus-mix',
      },
    ],
    totalValueNok: 499,
    stepReached: 'shipping',
    isRecovered: false,
    reminderSent: true,
    lastActiveAt: '2026-08-25T11:40:00Z',
    createdAt: '2026-08-25T11:20:00Z',
  },
];

// ==========================================
// 10. ADMIN BRUKERE & AUDIT LOGS
// ==========================================
export const INITIAL_ADMIN_USERS: AdminUser[] = [
  {
    id: 'adm-1',
    name: 'Kari Hundegodt (Eier)',
    email: 'kari@hundegodt.no',
    role: 'owner',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&h=200&q=80',
    lastLoginAt: '2026-08-26T08:00:00Z',
  },
  {
    id: 'adm-2',
    name: 'Ola Daglig Leder',
    email: 'ola@hundegodt.no',
    role: 'administrator',
    lastLoginAt: '2026-08-26T08:15:00Z',
  },
  {
    id: 'adm-3',
    name: 'Lars Lageransvarlig',
    email: 'lars.lager@hundegodt.no',
    role: 'warehouse',
    lastLoginAt: '2026-08-26T07:30:00Z',
  },
  {
    id: 'adm-4',
    name: 'Silje Kundeservice',
    email: 'silje@hundegodt.no',
    role: 'support',
    lastLoginAt: '2026-08-26T08:45:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    adminName: 'Kari Hundegodt (Eier)',
    adminEmail: 'kari@hundegodt.no',
    adminRole: 'owner',
    action: 'Prisjustering',
    entityType: 'product',
    entityId: 'prod-okselever',
    entityName: 'Naturlig Tørket Norsk Okselever (150g)',
    details: 'Satte kampanjepris til 129 kr (før 159 kr)',
    oldValue: '159 NOK',
    newValue: '129 NOK',
    timestamp: '2026-08-25T10:00:00Z',
  },
  {
    id: 'log-2',
    adminName: 'Lars Lageransvarlig',
    adminEmail: 'lars.lager@hundegodt.no',
    adminRole: 'warehouse',
    action: 'Ordrestatus endret',
    entityType: 'order',
    entityId: 'ord-10481',
    entityName: 'Ordre #HG-10481 (Thomas Berg)',
    details: 'Pakket ordre og genererte Bring sporingsnummer 370720124891991234NO',
    oldValue: 'Behandles',
    newValue: 'Sendt',
    timestamp: '2026-08-24T16:45:00Z',
  },
];
